Scale up BOSH director VM in "bbr" env
cloudfoundry/cf-deployment pull request #1012
Opened 2022-11-18 08:25 UTC by jochenehret

* load on director is too high and we sometimes see timeoutes when connecting to "uaa" process

### WHAT is this change about?

Scale up BOSH director VM to 4 core machine on "bbr" test environment.

### What customer problem is being addressed? Use customer persona to define the problem e.g. Alana is unable to...

"bbr-deploy" job often fails with timeouts: https://app-runtime-deployments.ci.cloudfoundry.org/teams/main/pipelines/cf-deployment/jobs/bbr-deploy/builds/117

### Please provide any contextual information.

PR for relint-envs: https://github.com/cloudfoundry/relint-envs/pull/4

### Has a cf-deployment including this change passed [cf-acceptance-tests](https://github.com/cloudfoundry/cf-acceptance-tests)?

N/A

### Does this PR introduce a breaking change? Please take a moment to read through the examples before answering the question.

- [ ] YES - please choose the category from below. Feel free to provide additional details.
- [x] NO

### How should this change be described in cf-deployment release notes?

PR is only for CI pipelines.

### Does this PR introduce a new BOSH release into the base cf-deployment.yml manifest or any ops-files?

- [ ] YES - please specify
- [x] NO

### Does this PR make a change to an experimental or GA'd feature/component?

- [ ] experimental feature/component
- [ ] GA'd feature/component

### Please provide Acceptance Criteria for this change?

"bbr-deploy" job has less fails.

### What is the level of urgency for publishing this change?

- [ ] **Urgent** - unblocks current or future work
- [x] **Slightly Less than Urgent**

### Tag your pair, your PM, and/or team!

> _It's helpful to tag a few other folks on your team or your team alias in case we need to follow up later._

2022-11-18 17:47 UTC, ctlong approved these changes

2022-11-18 23:44 UTC, davewalter requested changes
This looks good, apart from the  BBL plan-patch references in the `FIRST_DIR` params in the new combine-inputs tasks.

2022-11-18 23:44 UTC, davewalter commented on ci/pipelines/infrastructure.yml
> +      FIRST_DIR: plan-patches/bosh-lite-gcp
I think this should be `plan-patches/network-lb-gcp`.

2022-11-18 23:44 UTC, davewalter commented on ci/pipelines/infrastructure.yml
> +        FIRST_DIR: plan-patches/bosh-lite-gcp
I think this should also be `plan-patches/network-lb-gcp`.

2022-11-21 09:46 UTC, jochenehret commented
"update-infrastructure-bbr" job passed and BOSH director has been scaled up.

2022-11-21 09:46 UTC, merged