Integrate fips validation
cloudfoundry/cf-deployment pull request #1172
Opened 2024-04-08 11:06 UTC by jochenehret

### WHAT is this change about?

New ops file for replacing the default stemcell with a versioned FIPS stemcell. New job in "update-releases" pipeline to update the stemcell version.

### What customer problem is being addressed? Use customer persona to define the problem e.g. Alana is unable to...

Alana wants to have the FIPS stemcell validation integrated into the cf-deployment validate lifecycle.

### Please provide any contextual information.

https://github.com/cloudfoundry/cf-deployment/issues/1140

### Has a cf-deployment including this change passed [cf-acceptance-tests](https://github.com/cloudfoundry/cf-acceptance-tests)?

N/A

### Does this PR introduce a breaking change? Please take a moment to read through the examples before answering the question.

- [ ] YES - please choose the category from below. Feel free to provide additional details.
- [x] NO

### How should this change be described in cf-deployment release notes?

Not relevant for release notes.

### Does this PR introduce a new BOSH release into the base cf-deployment.yml manifest or any ops-files?

- [ ] YES - please specify
- [x] NO

### Does this PR make a change to an experimental or GA'd feature/component?

- [ ] experimental feature/component
- [ ] GA'd feature/component

### Please provide Acceptance Criteria for this change?

New Concourse job works: https://concourse.wg-ard.ci.cloudfoundry.org/teams/main/pipelines/update-releases/jobs/update-fips-stemcell/

### What is the level of urgency for publishing this change?

- [ ] **Urgent** - unblocks current or future work
- [x] **Slightly Less than Urgent**

### Tag your pair, your PM, and/or team!

> _It's helpful to tag a few other folks on your team or your team alias in case we need to follow up later._

2024-04-08 11:16 UTC, jochenehret commented
Pipeline has already been updated, but update-stemcell jobs have been paused until https://github.com/cloudfoundry/runtime-ci/pull/358 is merged.

2024-04-08 17:08 UTC, ctlong commented
Are we sure that we want to create an ops file if no one can actually use it without the password?

2024-04-25 18:30 UTC, ctlong approved these changes

2024-04-25 21:03 UTC, ctlong requested changes
This new ops file needs to be added to the unit tests

2024-04-26 16:22 UTC, ctlong approved these changes

2024-04-29 06:09 UTC, merged